services:
  nginx:
    image: nginx:latest
    build: ./
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc321
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
